// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementMVC.Data;

#nullable disable

namespace StudentManagementMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250619180129_changedPropStudent")]
    partial class changedPropStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementMVC.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            Department = "Bilgisayar Programcılığı",
                            StudentName = "Sedat"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Department = "YZ Mühendisliği",
                            StudentName = "Sıla"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Department = "TDE Öğretmenliği",
                            StudentName = "Mehmet"
                        },
                        new
                        {
                            Id = 4,
                            Age = 15,
                            Department = "Bilgisayar Mühendisliği",
                            StudentName = "Tarık"
                        },
                        new
                        {
                            Id = 5,
                            Age = 24,
                            Department = "Siber Güvenlik",
                            StudentName = "Süleyman"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
